# Generated by Django 4.0.4 on 2022-04-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_category_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='code',
        ),
    ]
